/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.12
 * Generated at: 2021-11-08 07:31:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import dao.goodsDAO;
import dto.goodsDTO;
import java.util.ArrayList;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


    	boolean login=false;
    	goodsDAO goods = new goodsDAO();
    	private ArrayList<goodsDTO> goods_dtos;
    
  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.goodsDAO");
    _jspx_imports_classes.add("dto.goodsDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\"/>\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\"/>\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>도도_고양이용품점</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"./resources/assets/favicon.ico\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("        integrity=\"sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2\" crossorigin=\"anonymous\">\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"./resources/css/styles.css\"/>\r\n");
      out.write("    </head>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    int pageSize = 4; // 한 페이지에 출력할 레코드 수

	// 페이지 링크를 클릭한 번호 / 현재 페이지
	String pageNum = request.getParameter("pageNum");
	if (pageNum == null){ // 클릭한게 없으면 1번 페이지
		pageNum = "1";
	}
	int currentPage = Integer.parseInt(pageNum);

	
	int count=0;
	count=goods.getCount();
	
	int endPage=(int) count/pageSize+1;
	
    
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <body>\r\n");
      out.write("        <!-- Responsive navbar-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand\" href=\"#!\">도도샵</a>\r\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                    <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"./index.jsp\">Home</a></li>\r\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">로그인</a></li>\r\n");
      out.write("                        ");

                        	if(login==true){ 
      out.write("\r\n");
      out.write("                        	<li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">로그아웃</a></li>\r\n");
      out.write("                        	<li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"#\">내 페이지</a></li>\r\n");
      out.write("                        ");
 	
                        	}
                       	
      out.write("\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Page header with logo and tagline-->\r\n");
      out.write("        <header class=\"py-5 bg-light border-bottom mb-4\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"text-center my-5\">\r\n");
      out.write("                    <h1 class=\"fw-bolder\">고양이가 직접 파는 제품</h1>\r\n");
      out.write("                    <p class=\"lead mb-0\">엄청난 품질과 서비스</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- Page content-->\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <!-- Blog entries-->\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <!-- Featured blog post-->\r\n");
      out.write("                    <div class=\"card mb-4\">\r\n");
      out.write("                        <a href=\"#!\"><img class=\"card-img-top\" src=\"./resources/image/대문사진.jpg\" width=\"850px\" height=\"350\"   alt=\"...\" /></a>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                           	<!-- <div class=\"small text-muted\">August 10, 2021</div> -->\r\n");
      out.write("                            <h2 class=\"card-title\">가게 주인이올시다</h2>\r\n");
      out.write("                            <p class=\"card-text\">많이들 둘러보고 구매부탁한다옹</p>\r\n");
      out.write("                            <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Nested row for non-featured blog posts-->\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <!-- Blog post-->\r\n");
      out.write("                            ");

                            	for(int i=0;i<2;i++) {
                            		goods_dtos=goods.getAllGoods(currentPage);	
                            
      out.write("\r\n");
      out.write("                            <div class=\"card mb-4\">\r\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"./resources/image/");
      out.print(goods_dtos.get(i).getName()+".jpg");
      out.write("\" width=\"700px\" height=\"350\"alt=\"...\" /></a>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <!-- <div class=\"small text-muted\">January 1, 2021</div>-->\r\n");
      out.write("                                    <h2 class=\"card-title h4\">");
      out.print(goods_dtos.get(i).getName());
      out.write("</h2>\r\n");
      out.write("                                    <p class=\"card-text\">");
      out.print(goods_dtos.get(i).getPrice());
      out.write("원</p>\r\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");

                            	}
                            
      out.write("\r\n");
      out.write("                            \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6\">\r\n");
      out.write("                            <!-- Blog post-->\r\n");
      out.write("                            ");

                            	for(int i=2;i<goods_dtos.size();i++) {
                            		
                            
      out.write("\r\n");
      out.write("                            <div class=\"card mb-4\">\r\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"./resources/image/");
      out.print(goods_dtos.get(i).getName()+".jpg");
      out.write("\" width=\"700px\" height=\"350\"alt=\"...\" /></a>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <!-- <div class=\"small text-muted\">January 1, 2021</div>-->\r\n");
      out.write("                                    <h2 class=\"card-title h4\">");
      out.print(goods_dtos.get(i).getName());
      out.write("</h2>\r\n");
      out.write("                                    <p class=\"card-text\">");
      out.print(goods_dtos.get(i).getPrice());
      out.write("원</p>\r\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            ");

                            	}
                            
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Pagination-->\r\n");
      out.write("                    <nav aria-label=\"Pagination\">\r\n");
      out.write("                        <hr class=\"my-0\" />\r\n");
      out.write("                        <ul class=\"pagination justify-content-center my-4\">\r\n");
      out.write("                            <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">Newer</a></li>\r\n");
      out.write("                            ");

                            	for(int i=1; i<=endPage;i++) {
                            
      out.write("\r\n");
      out.write("                            <li class=\"page-item active\" aria-current=\"page\"><a class=\"page-link\" href=\"./index.jsp?pageNum=");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("                           	");

                            	}
                           	
      out.write("\r\n");
      out.write("                            <!-- <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#!\">...</a></li>-->\r\n");
      out.write("                            \r\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#!\">Older</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </nav>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Side widgets-->\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <!-- Search widget-->\r\n");
      out.write("                    <div class=\"card mb-4\">\r\n");
      out.write("                        <div class=\"card-header\">Search</div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"input-group\">\r\n");
      out.write("                                <input class=\"form-control\" type=\"text\" placeholder=\"Enter search term...\" aria-label=\"Enter search term...\" aria-describedby=\"button-search\" />\r\n");
      out.write("                                <button class=\"btn btn-primary\" id=\"button-search\" type=\"button\">Go!</button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Categories widget-->\r\n");
      out.write("                    <div class=\"card mb-4\">\r\n");
      out.write("                        <div class=\"card-header\">Categories</div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("                                        <li><a href=\"#!\">사료</a></li>\r\n");
      out.write("                                        <li><a href=\"#!\">간식</a></li>\r\n");
      out.write("                                        <li><a href=\"#!\">장난감</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-sm-6\">\r\n");
      out.write("                                    <ul class=\"list-unstyled mb-0\">\r\n");
      out.write("                                        <li><a href=\"#!\">화장실</a></li>\r\n");
      out.write("                                        <li><a href=\"#!\">꾹꾹이</a></li>\r\n");
      out.write("                                        <li><a href=\"#!\">복실복실</a></li>\r\n");
      out.write("                                    </ul>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Side widget-->\r\n");
      out.write("                    <div class=\"card mb-4\">\r\n");
      out.write("                        <div class=\"card-header\">후원 계좌</div>\r\n");
      out.write("                        <div class=\"card-body\">국민 97539510065 류승윤</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"py-5 bg-dark\">\r\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2021</p></div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"./resources/css/scripts.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
